mstsv2/mstsv2app/users/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from mstsv2app.db import db
from mstsv2app.login import login_manager
from flask_login import UserMixin
from sqlalchemy_utils import ChoiceType


TYPES = [
    ('User','User'),
    ('Admin','Admin'),
    ('SuperAdmin','SuperAdmin')
]


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key=True)
    email = db.Column(db.String(150),unique=True,nullable=False)
    verified = db.Column(db.Boolean,nullable=False)
    verification_code = db.Column(db.String(150),unique=True)
    first_name = db.Column(db.String(150),nullable=True)
    last_name = db.Column(db.String(150),nullable=True)
    password_hash = db.Column(db.String(150),nullable=False)
    role = db.Column(ChoiceType(choices=TYPES))

    # the property decorator gives you a bunch of methods like
    # a setter, getter and deleter decorator.
    @property
    def password(self):
        raise AttributeError('cannot read the password')

    # will create the password hash when the password field is created
    # Default Values are:
    #    method = pbkdf2:sha1
    #    salt_length = 8

    @password.setter
    def password(self,password):
        self.password_hash = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_hash, password)

    def is_admin(self):
        return self.role == TYPES[1][0]

    def is_user(self):
        return self.role == TYPES[0][0]

    def is_superadmin(self):
        return self.role == TYPES[2][0]


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

mstsv2/mstsv2app/users/forms.py
from flask_wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import Required, Length, Email, EqualTo, ValidationError
from models import User

class LoginForm(Form):
    email = StringField('Email',validators=[Required(), Length(1,64),Email()])
    password = PasswordField('Password',validators=[Required()])
    remember_me = BooleanField('Keep me logged in')
    submit = SubmitField('Log in')


class RegistrationForm(Form):
    email = StringField('Email',validators=[Required(), Length(1,64),Email()])
    password = PasswordField('Password',validators=[Required(),
    EqualTo('password_confirmation',message="Passwords must match")])
    password_confirmation = PasswordField('Confirm Password',validators=[ Required()])
    submit = SubmitField('Register')
    def validate_email(self,field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered')

class SettingsForm(Form):
    email = StringField('Email',validators=[Required(), Length(1,64),Email()])
    password = PasswordField('Password',validators=[EqualTo('password_confirmation',
    message="Passwords must match")])
    password_confirmation = PasswordField('Confirm Password')
    submit = SubmitField('Register')
    def validate_email(self,field):
        user = User.query.filter_by(email=field.data).first()
        if user:
            print(field.data)
            print(user.email)
            if field.data != user.email:
                raise ValidationError('Email already registered')

class ForgotPasswordForm(Form):
    email = StringField('Email',validators =[Required(),Length(1,64),Email()])
    submit = SubmitField('Register')

mstsv2/mstsv2app/users/routes.py
from flask import Blueprint
from flask_restful import Api
from resources import UserList, UserUpdate, UserVerify

from views import login, logout, register, verify_account, account_settings
from views import reauthenticate, delete_account, forgot_password


users_blueprint = Blueprint('users',__name__)


# Flask Restful API
users_api = Api(users_blueprint)




# REST API Component
users_api.add_resource(UserList,'')
users_api.add_resource(UserUpdate,'/<int:id>')
users_api.add_resource(UserVerify,'/verify')


# Views import

# Login and Logout
users_blueprint.add_url_rule('/login',view_func=login,methods=['POST','GET'])
users_blueprint.add_url_rule('/logout',view_func=logout,methods=['POST','GET'])
users_blueprint.add_url_rule('/reauthenticate',view_func=reauthenticate,methods=['POST','GET'])

# Registration
users_blueprint.add_url_rule('/register',view_func=register,methods=['POST','GET'])
users_blueprint.add_url_rule('/register/verify/<verification_code>',view_func=verify_account,methods=['GET'])

# Account Views
users_blueprint.add_url_rule('/account/settings',view_func=account_settings,methods=['GET','POST'])
users_blueprint.add_url_rule('/account/settings/delete',view_func=delete_account,methods=['POST'])
users_blueprint.add_url_rule('/acccount/password/recover',view_func=forgot_password,methods=['POST','GET'])

mstsv2/mstsv2app/users/views.py
from flask import render_template, flash, request,redirect, url_for
from flask_login import login_user,logout_user, login_required, current_user, fresh_login_required
from flask_mail import Message
from mstsv2app.mail import mail
from mstsv2app.tools.error_reporting import flash_errors
from sqlalchemy.orm.exc import NoResultFound, MultipleResultsFound
from models import User, TYPES, db
from forms import LoginForm, RegistrationForm, SettingsForm, ForgotPasswordForm
import random
import string
import socket

def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.homepage'))
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and user.verify_password(form.password.data):
            if user.verified:
                login_user(user,remember=form.remember_me.data)
                return redirect(request.args.get('next') or url_for('main.homepage'))
            else:
                flash('Please verify your email address before logging in.','alert-danger')
        else:
            flash('Invalid username or password.','alert-danger')

    return render_template('users/login.html',form=form)

def reauthenticate():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and user.verify_password(form.password.data):
            if user.verified:
                login_user(user,remember=form.remember_me.data)
                return redirect(request.args.get('next') or url_for('main.homepage'))
            else:
                flash('Please verify your email address before logging in.','alert-danger')
        else:
            flash('Invalid username or password.','alert-danger')

    return render_template('users/login.html',form=form)



@login_required
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('main.homepage'))


def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.homepage'))
    form = RegistrationForm(request.form)
    if form.validate_on_submit():
        verification_code = ''.join([ random.choice(
                                string.ascii_uppercase +
                                string.ascii_lowercase +
                                string.digits) for _ in range(1,48) ])
        user = User(email=form.email.data,
                    verified=False,
                    verification_code = verification_code,
                    password=form.password.data,
                    role = TYPES[0][0]) # Get the User Type by Default
        db.session.add(user)
        db.session.commit()

        msg = Message('Welcome to MSTS',
                      sender="from@example.com",
                      recipients=[form.email.data],
                      )
        msg.html = render_template('users/registration_email.html',
                                    verification_code = verification_code)
        try:
            mail.send(msg)
        except socket.error as e:
            print("Message not successfully sent")

        flash('Successful registration. Please validate your email before logging in.')
        return redirect(url_for('users.login'))
    return render_template('users/register.html',form=form)

@login_required
@fresh_login_required
def account_settings():
    form = SettingsForm(request.form)
    if form.validate_on_submit():
        current_user.email = form.email.data
        if form.password.data:
            current_user.password = form.password.data

        flash("Settings Updated")

        db.session.add(current_user)
        db.session.commit()

    form.email.data = current_user.email

    flash_errors(form)
    return render_template('users/account_settings.html',form =form)

@login_required
@fresh_login_required
def delete_account():
    user_id = current_user.id
    user = User.query.get(user_id)
    logout_user()
    db.session.delete(user)
    db.session.commit()
    flash("Account Successfully deleted. We hope to see you again soon!")

    # may have to refactor and send an email when an account gets deleted

    return redirect(url_for("main.homepage"))


def verify_account(verification_code):
    try:
        user = User.query.filter_by(verification_code=verification_code).one()
        user.verified = True
        db.session.add(user)
        db.session.commit()

    except NoResultFound:
        return redirect(url_for('main.homepage'))

    except MultipleResultsFound:
        return redirect(url_for('main.homepage'))

    flash("Thank you for verifying your account, you may now login.")
    return redirect(url_for('users.login'))

def forgot_password():
    form = ForgotPasswordForm(request.form)
    if form.validate_on_submit():
        # generating a random token to send to the user email
        user_email = form.email.data
        try:
            print("here")
            user = User.query.filter_by(email=user_email).one()
            verification_code = verification_code = ''.join([ random.choice(
                                    string.ascii_uppercase +
                                    string.ascii_lowercase +
                                    string.digits) for _ in range(1,48) ])


            msg = Message('MSTS Password Reset',
                              sender="from@example.com",
                              recipients=[user_email],
                              )
            msg.html = render_template('users/forgot_password_email.html',verification_code = verification_code)
            try:
                mail.send(msg)
            except socket.error as e:
                print("Message not successfully sent")

        except MultipleResultsFound as e:
            pass
        except NoResultFound as e:
            pass


        flash("If this email address has a registered account, we have sent an email with instructions on how to recover your account.","alert-success")
    print(form.errors)
    return render_template('users/forgot_password.html',form=form)

mstsv2/mstsv2app/templates/users/account_settings.html
{% extends 'base.html' %}
{% import 'render_field.html' as render_fields %}

{% block subtitle %} Login {% endblock %}

{% block css %}
<style type="text/css">
.transition{
    opacity:0;
}
.btn-msts{
  background:rgb(111, 194, 150);
}
</style>
{% endblock %}



{% block content %}
<div class="container transition">
  <div id="main_title"><h1 class="page-header" style="display:inline">Settings</h1></div>
  <br />
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#account_info" aria-controls="account_info" role="tab" data-toggle="tab">Account Info</a></li>
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
    <li role="presentation"><a href="#delete_account" aria-controls="profile" role="tab" data-toggle="tab">Delete Account</a></li>
  </ul>
  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="account_info">
      <br />
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <br />
              <h2>Account Information</h2>
              <table class="table table-responsive">
                <tbody>
                  <tr>
                    <td>Auto Generated Avatar</td>
                    <td><img src="{{ current_user.email|gravatar }}"></img></td>
                  </tr>
                  <tr>
                    <td>Account Status</td>
                    <td>{{ current_user.role }}</td>
                  </tr>
                </tbody>
              </table>
        </div>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane" id="settings">
      <br />
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <br />
              <h2>User Settings</h2>
              <form method='POST' action="{{ url_for('users.account_settings') }}">
                {{ form.hidden_tag() }}
                <label>{{ form.email.label }}</label>
                {{ form.email(class="form-control") }}
                <br />
                <label>{{ form.password.label }}</label>
                {{ form.password(class="form-control") }}
                <br />
                <label>{{ form.password_confirmation.label }} </label>
                {{ form.password_confirmation(class="form-control") }}
                <br />
                <input class="btn btn-msts" type="submit" value="Save" />
              </form>
        </div>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane" id="delete_account">
      <h2></h2>
      <p>
        Delete all information relating to your account. We will not be able to retrieve
        your information.
      </p>
      <form method="POST" onclick="return confirm('Are you sure you want to delete your account?')" action="{{ url_for('users.delete_account') }}">
        <input type="submit" class="btn btn-danger" />
      </form>
    </div>
  </div>
{% endblock %}



{% block js %}
<script src="{{ url_for('static',filename='js/jquery.transit.min.js')}}"></script>

<script type="text/javascript">
$(document).ready(function() {
    $('.transition').transition({opacity:1});

});
</script>
{% endblock %}

mstsv2/mstsv2app/templates/users/forgot_password.html
{% extends 'base.html' %}

{% block subtitle %} Forgot Password {% endblock %}

{% block css %}
<style type="text/css">
.transition{
    opacity:0;
}
</style>
{% endblock %}



{% block content %}
<div class="container transition">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div id="main_title"><h1 class="page-header" style="display:inline">Forgot Password</h1></div>
      <br />
      {% from 'render_field.html' import render_field_errors %}
      <form method='POST' action="{{ url_for('users.forgot_password')}}">
        {{ form.hidden_tag() }}
        <label>{{ form.email.label }}</label>
        {{ render_field_errors(form.email) }}
        {{ form.email(class='form-control') }}
        <br />
        {{ form.submit(class='btn btn-default') }}
      </form>
    </div>
  </div>
</div>
{% endblock %}



{% block js %}
<script src="{{ url_for('static',filename='js/jquery.transit.min.js')}}"></script>

<script type="text/javascript">
$(document).ready(function() {
    $('.transition').transition({opacity:1});

});
</script>
{% endblock %}

mstsv2/mstsv2app/templates/users/forgot_password_email.html
<h1>MSTS - Forgot Password</h1>

<p>
We received an email that asked to reset your password.
Please click the link below to reset your password.
If you received this in error or did not make a request
please contact us immedietly.
</p>
<a href="http://127.0.0.1:5000/users/verify/{{ verification_code }}">Password Reset</a>

Best Wishes,

- MSTS Team

mstsv2/mstsv2app/templates/users/login.html
{% extends 'base.html' %}
{% from 'render_field.html' import render_field_errors %}

{% block subtitle %} Login {% endblock %}

{% block css %}
<style type="text/css">
.transition{
    opacity:0;
}
</style>
{% endblock %}



{% block content %}
<div class="container transition">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div id="main_title"><h1 class="page-header" style="display:inline">Login</h1></div>
      <br />
      <div class="panel panel-default">
        <div class="panel-body">
          <form method='POST' action="{{ url_for('users.login') }}">
            {{ form.hidden_tag() }}
              <label>{{ form.email.label }}</label>
              {{ render_field_errors(form.email) }}
              {{ form.email(class='form-control') }}
              <br />
              <label>{{ form.password.label }}</label>
              {{ render_field_errors(form.password) }}
              {{ form.password(class='form-control') }}
              <br />
              <label>{{ form.remember_me.label }}</label>
              {{ render_field_errors(form.remember_me) }}
              {{ form.remember_me() }}
              <br />
              {{ form.submit(class='btn btn-default') }}
          </form>
          <a href="{{ url_for('users.forgot_password') }}"><i>Forgot Password</i></a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}



{% block js %}
<script src="{{ url_for('static',filename='js/jquery.transit.min.js')}}"></script>

<script type="text/javascript">
$(document).ready(function() {
    $('.transition').transition({opacity:1});

});
</script>
{% endblock %}

mstsv2/mstsv2app/templates/users/register.html
{% extends 'base.html' %}
{% from 'render_field.html' import render_field_errors %}

{% block subtitle %} Login {% endblock %}

{% block css %}
<style type="text/css">
.transition{
    opacity:0;
}
</style>
{% endblock %}



{% block content %}
<div class="container transition">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div id="main_title"><h1 class="page-header" style="display:inline">Registration</h1></div>
      <br />
      <div class="panel panel-default">
        <div class="panel-body">
          <form method='POST' action="{{ url_for('users.register') }}">
              {{ form.hidden_tag() }}

              <label>{{ form.email.label }}</label>
              {{ render_field_errors(form.email) }}
              {{ form.email(class='form-control') }}
              <br />
              <label>{{ form.password.label }}</label>
              {{ render_field_errors(form.password) }}
              {{ form.password(class='form-control') }}
              <br />
              <label>{{ form.password_confirmation.label }}</label>
              {{ render_field_errors(form.password_confirmation) }}
              {{ form.password_confirmation(class='form-control')}}
              <br />
              {{ form.submit(class='btn btn-default') }}
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}



{% block js %}
<script src="{{ url_for('static',filename='js/jquery.transit.min.js')}}"></script>

<script type="text/javascript">
$(document).ready(function() {
    $('.transition').transition({opacity:1});

});
</script>
{% endblock %}

mstsv2/mstsv2app/templates/users/registration_email.html
<h1>Welcome to the MSTS Website</h1>

<p>
   We are happy to see you join. Please verify your account by clicking the
   link below. If you did not create this account, please disregard this message.
</p>
<a href="http://127.0.0.1:5000/users/register/verify/{{ verification_code }}">Link to Verify Password</a>

Best Wishes,

- MSTS Team

mstsv2/mstsv2app/templates/users/render_field.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>

{% endmacro %}