mstsv2/mstsv2app/blogs/routes.py
from flask import Blueprint, render_template



blogs_blueprint = Blueprint('blogs',__name__)


@blogs_blueprint.route('')
def blogs():
    return render_template('blogs/blogs.html')

mstsv2/mstsv2app/main/routes.py
from flask import Blueprint, render_template

main_blueprint = Blueprint("main",__name__)

@main_blueprint.route('')
def homepage():
	return render_template('index.html')

@main_blueprint.route('mission')
def mission_statement():
	return render_template('mission_statement.html')

mstsv2/mstsv2app/templates/base.html
<html>
<head>
	<title>MSTS - {% block subtitle %}Official Website{% endblock %}</title>


	<link rel="shortcut icon" href="{{ url_for('static',filename='img/logo/trading_society_logo.ico')}}" />

	<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename="css/bootstrap.min.css") }}" / >
	<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/base.css' )}}" />
	{% block css %}
	{% endblock %}
</head>
<body>
	<div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="{{ url_for('main.homepage') }}" class="navbar-brand">
			  <div class="header-img"><img class="img-responsive logo-size"  src="{{ url_for('static',filename='img/logo/trading_society_logo.jpg') }}"></img></div>
		  </a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
			  			<li>
                <a href="{{ url_for('main.mission_statement') }}">Mission Statement</a>
              </li>
			  			<li>
                <a href="{{ url_for('resources.list_resources') }}">Resources</a>
              </li>
			  			<li>
                <a href="{{ url_for('blogs.blogs') }}">Blog</a>
              </li>
          </ul>
					<ul class="nav navbar-nav pull-right">
						{% if current_user.is_authenticated %}
						<li>
							<a href="{{ url_for('users.account_settings') }}">Settings</a>
						</li>
						<li>
							<a href="{{ url_for('users.logout') }}">Logout</a>
						</li>
						{% else %}
						<li>
							<a href="{{ url_for('users.register' )}}">Register</a>
						</li>
						<li>
							<a href="{{ url_for('users.login' )}}">Login</a>
						</li>
						{% endif %}
					</ul>
        </div>
      </div>
    </div>
	<div class="container"><div class="row" style="height:100px;"></div></div>
	{% with messages = get_flashed_messages() %}
		{% if messages %}
    		{% for message in messages %}
      		<div class="{{ category }}" >{{ message }}</li>
    		{% endfor %}
  	{% endif %}
	{% endwith %}
	{% block content %}
	{% endblock %}





	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{{ url_for('static',filename='js/bootstrap.min.js')}}"></script>

	{% block js %}

	{% endblock %}
</body>

</html>

mstsv2/mstsv2app/templates/index.html
{% extends 'base.html' %}

{% block subtitle %} Homepage {% endblock %}

{% block css %}
<style type="text/css">
.transition{
    opacity:0;
}
</style>
{% endblock %}



{% block content %}
<div class="container transition">
    <div class="row">
        <div id="main_title"><h1 class="page-header" style="display:inline"></h1></div>
    </div>
</div>
{% endblock %}



{% block js %}
<script src="{{ url_for('static',filename='js/typed.js')}}"></script>
<script src="{{ url_for('static',filename='js/jquery.transit.min.js')}}"></script>

<script type="text/javascript">
$(document).ready(function() {
    $('.transition').transition({opacity:1});
    $('#main_title > .page-header').typed({
        strings:["McGill Students Trading Society"],
        typeSpeed: 0
    });
});
</script>
{% endblock %}

mstsv2/mstsv2app/templates/mission_statement.html
{% extends 'base.html' %}

{% block subtitle %} Mission Statement {% endblock %}


{% block css %}
<style type="text/css">
.transition{
    opacity:0;
}
</style>
{% endblock %}



{% block content %}
<div class="container transition">
    <div class="row">
        <div id="main_title"><h1 class="page-header" style="display:inline">Mission Statement</h1></div>
    </div>
</div>
<div class="container transition">
    <br />
    <br />
    <div class="row">
        <div class="col-sm-12" id="videoplayer">
        <iframe src="https://www.youtube.com/embed/G2Y9vb-7ZyM" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
</div>
{% endblock %}


{% block js %}
<script src="{{ url_for('static',filename='js/jquery.transit.min.js')}}"></script>
<script src="{{ url_for('static', filename='js/jquery.fitvids.js') }}"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('.transition').transition({opacity:1});
     $("#videoplayer").fitVids();
});
</script>
{% endblock %}

mstsv2/mstsv2app/templates/render_field.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

{% macro render_field_errors(field) %}
  {% if field.errors %}
    {% for error in field.errors %}
      <div class="alert-danger">{{ error }}</div>
    {% endfor %}
  {% endif %}
{% endmacro %}